export const demoData = {
  series: [
    {
      id: 1,
      title: "Creator Spotlight",
      cadence: "weekly",
      status: "active",
      owner_id: 1,
      created_at: "2026-03-01T10:00:00Z",
    },
    {
      id: 2,
      title: "Patch Notes Live",
      cadence: "monthly",
      status: "draft",
      owner_id: 2,
      created_at: "2026-03-10T14:30:00Z",
    },
    {
      id: 3,
      title: "Behind The Build",
      cadence: "biweekly",
      status: "archived",
      owner_id: 3,
      created_at: "2026-02-18T09:15:00Z",
    },
  ],
  streams: [
    {
      id: 1,
      series_id: 1,
      title: "Episode 01 Raw Capture",
      date: "2026-03-02T17:00:00Z",
      platform: "Twitch",
      duration_seconds: 5400,
      status: "processed",
      created_at: "2026-03-02T19:00:00Z",
    },
    {
      id: 2,
      series_id: 1,
      title: "Episode 02 Interview",
      date: "2026-03-09T17:00:00Z",
      platform: "YouTube",
      duration_seconds: 4200,
      status: "ready",
      created_at: "2026-03-09T18:30:00Z",
    },
    {
      id: 3,
      series_id: 2,
      title: "Patch Notes March",
      date: "2026-03-12T20:30:00Z",
      platform: "Kick",
      duration_seconds: 3600,
      status: "archived",
      created_at: "2026-03-12T21:45:00Z",
    },
  ],
  projects: [
    {
      id: 1,
      title: "Creator Spotlight - Spring Cut",
      description: "Highlight reel and clipped segments for Spring campaign.",
      series_id: 1,
      owner_id: 2,
      streams: [1, 2],
      status: "in_review",
      created_at: "2026-03-13T11:00:00Z",
    },
    {
      id: 2,
      title: "Patch Notes Episode Pack",
      description: "Long-form + shorts package for patch release coverage.",
      series_id: 2,
      owner_id: 1,
      streams: [3],
      status: "draft",
      created_at: "2026-03-14T08:45:00Z",
    },
    {
      id: 3,
      title: "Behind The Build Highlights",
      description: "Curated moments for social clips and recap post.",
      series_id: 3,
      owner_id: 3,
      streams: [],
      status: "published",
      created_at: "2026-03-15T16:20:00Z",
    },
  ],
  episodes: [
    {
      id: 1,
      project_id: 1,
      series_id: 1,
      title: "Creator Spotlight Ep. 01",
      description: "Edited highlight package for the first creator feature.",
      publish_status: "ready",
      destination: "YouTube",
      created_at: "2026-03-16T09:00:00Z",
    },
    {
      id: 2,
      project_id: 2,
      series_id: 2,
      title: "Patch Notes Recap",
      description: "Patch release breakdown and timeline recap.",
      publish_status: "published",
      destination: "Podcast",
      created_at: "2026-03-17T13:25:00Z",
    },
    {
      id: 3,
      project_id: 3,
      series_id: 3,
      title: "Behind The Build Snippets",
      description: "Short-form clips cut for social channels.",
      publish_status: "ready",
      destination: "TikTok",
      created_at: "2026-03-18T18:10:00Z",
    },
  ],
  users: [
    {
      id: 1,
      email: "alex.editor@example.com",
      name: "Alex Rivera",
      role: "editor",
      created_at: "2026-02-01T09:00:00Z",
    },
    {
      id: 2,
      email: "morgan.reviewer@example.com",
      name: "Morgan Lee",
      role: "reviewer",
      created_at: "2026-02-05T10:15:00Z",
    },
    {
      id: 3,
      email: "sam.admin@example.com",
      name: "Sam Patel",
      role: "admin",
      created_at: "2026-01-28T14:45:00Z",
    },
  ],
};
